#!/bin/bash
# Copyright (C) 2025 - Juan Carlos Prieto <nilibox@nilibox.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses>.

# Path to the Qt location
QTDIR=~/Qt/6.7.3/macos

# Path to the generated release
RLDIR=~/niliBOX/build/Desktop-Release

# Apple development team
SIGN="Apple Development: jcarlos.prieto@gmail.com (GCZ89RMD87)"

if [ ! -d $RLDIR ]; then
    echo Release directory not found
    exit 1
fi

echo Generating macOS distribution

rm -r ~/niliBOX.app
cp -r $RLDIR/niliBOX.app ~/niliBOX.app
cp $QTDIR/bin/lrelease ~/niliBOX.app/Contents/MacOS
cp $QTDIR/libexec/rcc ~/niliBOX.app/Contents/MacOS
$QTDIR/bin/macdeployqt6 ~/niliBOX.app -qmldir=../resources -appstore-compliant
rm -r ~/niliBOX.app/Contents/PlugIns/sqldrivers
codesign --force --verify --deep --options runtime --entitlements ~/niliBOX.app/Contents/niliBOX.entitlements --sign $SIGN ~/niliBOX.app
hdiutil create -volname niliBOX -srcfolder ~/niliBOX.app -ov -format UDZO ~/niliBOX-macos.dmg
mkdir _downloads
rm -rf macos
mkdir macos
cp -R ~/niliBOX.app macos/niliBOX.app

echo Generating _downloads/niliBOX-macos.dmg

cp ~/niliBOX-macos.dmg _downloads/niliBOX-macos.dmg
rm -r ~/niliBOX.app
rm ~/niliBOX-macos.dmg
